import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { items, photosFirst, totals, money, price, categories, priorities, type Item } from './domain.ts';

const esc = (value: string) => value.replace(/[&<>"']/g, char => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[char] ?? char));
const link = (url: string, label: string, attributes = '') => `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" ${attributes}>${esc(label)}</a>`;
const list = (title: string, rows: string[]) => rows.length ? `<h4>${title}</h4><ul>${rows.map(row => `<li>${esc(row)}</li>`).join('')}</ul>` : '';
const options = (rows: string[]) => rows.map(row => `<option>${esc(row)}</option>`).join('');
const priceLabels: Record<string, string> = { manual:'TWOJA CENA', estimate:'SZACUNEK', reference:'CENA REFERENCYJNA' };
const priceLabel = (item: Item) => priceLabels[item.priceKind] ?? (item.url ? new URL(item.url).hostname.replace(/^www\./, '') : '');
function card(item: Item) {
  const unit = item.purchaseUnit === 'opak.' ? 'opakowanie' : item.purchaseUnit === 'zest.' ? 'zestaw' : 'sztukę';
  const sources = [...new Set([item.priceUrl, ...item.sourceUrls].filter(Boolean))];
  return `<article class="product-card ${item.status === 'excluded' ? 'excluded' : ''}" data-id="${esc(item.id)}" data-category="${esc(item.category)}" data-priority="${esc(item.priority)}" data-consult="${item.consult}" data-photo="${Boolean(item.image)}">
    ${item.image ? `<a class="product-photo" href="${esc(item.url || item.image)}" target="_blank" rel="noopener noreferrer"><img src="${esc(item.image)}" alt="${esc(item.imageAlt || item.model)}" width="130" height="138" loading="eager" decoding="async"></a>` : ''}
    <div class="product-body"><p class="eyebrow">${esc(item.category)}<span class="badge priority-${priorities.indexOf(item.priority)}">${esc(item.priority)}</span>${item.original ? '<span class="type-badge">TWÓJ TYP</span>' : ''}</p>
      <h3>${esc(item.name)}</h3><p class="model">${item.url ? link(item.url, item.model || 'Zobacz produkt') : esc(item.model || 'Typ do wyboru')}</p>
      <p class="description">${esc(item.description)}</p><div class="item-meta">${item.quantity > 1 ? `<span>${item.quantity} ${esc(item.purchaseUnit)} · cena za ${unit} ${money(item.cents ?? 0)}</span>` : ''}${item.consult ? '<span>Do omówienia</span>' : ''}${item.status === 'bought' ? '<span>Kupione</span>' : ''}${item.status === 'excluded' ? '<span>Poza budżetem</span>' : ''}</div>
    </div><div class="product-price"><strong>${esc(price(item))}</strong><small>${esc(priceLabel(item))}</small>${item.url ? link(item.url, 'Zobacz w sklepie ↗', `class="outline shop-link" aria-label="Zobacz w sklepie: ${esc(item.name)}"`) : ''}<button class="ghost detail-toggle no-print" aria-expanded="false" aria-controls="details-${esc(item.id)}">Szczegóły i notatki</button></div>
    <div class="product-details" id="details-${esc(item.id)}" hidden>${item.availability ? `<p class="availability">${esc(item.availability)}</p>` : ''}${list('Cechy produktu', item.features)}${list('Do omówienia', item.questions)}${item.notes ? `<h4>Nasze notatki</h4><p class="notes">${esc(item.notes)}</p>` : ''}${sources.length ? `<h4>Źródła i informacje o cenie</h4><ul class="source-links">${sources.map(url => `<li>${link(url, url)}</li>`).join('')}</ul>` : ''}${item.checked ? `<small>Informacja o cenie z ${esc(item.checked)}</small>` : ''}</div>
  </article>`;
}
const budget = totals(items);
const html = `<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Wyprawka Justyny: wybrane produkty, zdjęcia, ceny i pytania do wspólnych decyzji."><meta name="color-scheme" content="light"><title>Małe początki | Wyprawka Justyny</title><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./style.css"><script src="./app.js" defer></script></head><body><main class="workspace" data-view="list">
  <header class="topbar"><a class="brand" href="./"><span class="brand-icon" aria-hidden="true">✦</span><span>Małe początki<small>WYPRAWKA JUSTYNY</small></span></a><span class="date-note no-print">Lista do wspólnych decyzji</span></header>
  <div class="page-heading"><div><p class="eyebrow">WSZYSTKO NA DOBRY POCZĄTEK</p><h1>Nasza wyprawka<span>.</span></h1></div><p>Twoje typy, wspólne decyzje.</p></div>
  <section class="budget" aria-label="Podsumowanie kosztów"><div><p>Cała lista · ceny i szacunki</p><strong>${money(budget.total)}</strong><small>Bez dostawy. Szacunki oraz ceny „od” i referencyjne wliczone.</small></div><div><p>Wyprawka bez opcjonalnych</p><strong>${money(budget.withoutOptional)}</strong><small>Na start i na później · bez dostawy</small></div><div><p>W tym kwoty szacunkowe</p><strong>${money(budget.estimated)}</strong><small>${budget.estimatedCount} pozycji · ceny do potwierdzenia przed zakupem</small></div></section>
  <div class="tabbar no-print"><div class="view-tabs" role="tablist" aria-label="Widok listy"><button role="tab" aria-selected="true" aria-controls="products" id="list-tab" data-view="list">Lista wyprawki <span class="count">${items.length}</span></button><button role="tab" aria-selected="false" aria-controls="products" id="consult-tab" data-view="consult" tabindex="-1">Do konsultacji <span class="count">${items.filter(item => item.consult && item.status !== 'excluded').length}</span></button></div><span class="date-note">Ceny sklepowe sprawdzone: 04.10.2026</span></div>
  <div class="toolbar"><div class="list-heading"><h2 id="list-title">Rzeczy do małych i wielkich chwil</h2><p>${items.filter(item => item.original).length} Twoich typów + podstawy do uzupełnienia</p></div><div class="list-tools no-print"><button class="primary" id="print">↓ Zapisz listę jako PDF</button><div class="filters"><select aria-label="Filtr kategorii" id="category">${options(['Wszystkie kategorie', ...categories])}</select><select aria-label="Filtr priorytetu" id="priority">${options(['Wszystkie priorytety', ...priorities])}</select></div></div></div>
  <p class="pdf-note no-print" role="status" id="pdf-note">PDF całej listy ze zdjęciami i klikalnymi linkami. W oknie drukowania wybierz „Zapisz jako PDF”.</p>
  <div class="legend"><span><i class="legend-line"></i>Na start: podstawy przed narodzinami</span><span>Opcjonalne: dla wygody</span><span>Na później: gdy przyjdzie czas</span></div><div id="products" role="tabpanel" aria-labelledby="list-tab">${photosFirst(items).map(card).join('\n')}</div><p class="empty no-print" hidden>Brak produktów dla wybranych filtrów.</p>
  <div class="sources-box"><h3>Lista na start, bez presji na wszystko</h3><p>Podział na priorytety to propozycja do dostosowania do Waszego domu, pory roku i sposobu karmienia. Ilości podstawowych rzeczy są punktem wyjścia. Brak ceny nie oznacza 0 zł.</p><p>${link('https://www.nhs.uk/best-start-in-life/pregnancy/preparing-for-labour-and-birth/what-to-buy-for-your-newborn-baby/', 'Podstawa listy: NHS')} · ${link('https://www.nhs.uk/best-start-in-life/baby/baby-basics/newborn-and-baby-sleeping-advice-for-parents/safe-sleep-advice-for-babies/', 'Bezpieczny sen: NHS')}</p></div><footer>Małe początki · jedna lista, mniej rzeczy do pamiętania.</footer></main></body></html>`;
const output = resolve(process.argv[2] ?? 'docs');
mkdirSync(output, { recursive: true });
writeFileSync(join(output, 'index.html'), html.replace(/[ \t]+$/gm, ''));
writeFileSync(join(output, '.nojekyll'), '');
for (const file of ['style.css', 'app.js', 'favicon.svg']) copyFileSync(file, join(output, file));
console.log(`Gotowe: ${items.length} produktów; cała lista ${money(budget.total)}; bez opcjonalnych ${money(budget.withoutOptional)}.`);
